#pragma once

#include <GROOVE/LED/LightEmitter.h>
#include <GROOVE/LED/Pattern/BasePattern.h>
#include <GROOVE/LED/Pattern/LineBackPattern.h>
#include <GROOVE/LED/Pattern/LineFingerBackPattern.h>
#include <GROOVE/LED/Pattern/LineFingerForwardPattern.h>
#include <GROOVE/LED/Pattern/LineForwardPattern.h>
#include <GROOVE/LED/Pattern/LineRingPattern.h>
#include <GROOVE/LED/Pattern/PeaceGesturePattern.h>
#include <GROOVE/LED/Pattern/PointGesturePattern.h>
#include <GROOVE/LED/Pattern/RainbowPattern.h>
#include <GROOVE/LED/Pattern/RingToLinePattern.h>
#include <GROOVE/LED/Pattern/RockGesturePattern.h>
#include <GROOVE/LED/Pattern/UniqueDevicePattern.h>

#include <GROOVE/LED/Pattern/PV/Scene10Pattern.h>
#include <GROOVE/LED/Pattern/PV/Scene11Pattern.h>
#include <GROOVE/LED/Pattern/PV/Scene1Pattern.h>
#include <GROOVE/LED/Pattern/PV/Scene2Pattern.h>
#include <GROOVE/LED/Pattern/PV/Scene3Pattern.h>
#include <GROOVE/LED/Pattern/PV/Scene4Pattern.h>
#include <GROOVE/LED/Pattern/PV/Scene5Pattern.h>
#include <GROOVE/LED/Pattern/PV/Scene6-1Pattern.h>
#include <GROOVE/LED/Pattern/PV/Scene6-2Pattern.h>
#include <GROOVE/LED/Pattern/PV/Scene6-3Pattern.h>
#include <GROOVE/LED/Pattern/PV/Scene6-4Pattern.h>
#include <GROOVE/LED/Pattern/PV/Scene6-5Pattern.h>
#include <GROOVE/LED/Pattern/PV/Scene6-6Pattern.h>
#include <GROOVE/LED/Pattern/PV/Scene7Pattern.h>
#include <GROOVE/LED/Pattern/PV/Scene8Pattern.h>
#include <GROOVE/LED/Pattern/PV/Scene9Pattern.h>
